version: '3.7'
services: 
    rabbitmq:
        image: rabbitmq:management
        container_name: rabbitmq
        restart: always
        ports: 
            # - 5672:5672
            - 15672:15672
        networks: 
            - microservices

    web_gateway:
        build: gateway/
        ports: 
            - 80:8000
        networks: 
            - microservices

    db_rpc:
        build: db_rpc/
        networks: 
            - microservices
        
networks: 
    microservices:
        external:
            name: microservices_network